name: CI + Pages Deploy

on:
  push:
    branches: ['**']        # run checks on every branch
  pull_request:
    branches: ['**']        # run checks on every PR

permissions:
  contents: read
  pages: write              # needed only for deploy job (safe to keep here)
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci
        env:
          NODE_ENV: development

      - name: Security audit
        run: npx audit-ci --moderate --skip-dev

      - name: Lint
        run: npx eslint src --ext .ts,.tsx --max-warnings=10

      - name: TypeScript check
        run: npx tsc --noEmit

      - name: Tests
        run: npm test -- --coverage --watchAll=false

      - name: Build (Vite)
        run: npm run build
        env:
          NODE_ENV: production
          VITE_API_URL: '/api'
          VITE_APP_VERSION: ${{ github.sha }}

      # SPA routing fix for GitHub Pages
      - name: Add 404.html
        run: cp dist/index.html dist/404.html

      # Always keep the artifact for debugging; deploy job will pick it only on main
      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: dist

  deploy:
    # Only run on pushes to main (not PRs, not other branches)
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    needs: build-and-test
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
